easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Booking
#        - App\Entity\User
     site_name: 'Box of Heroes'
     entities:
         Booking:
             class: App\Entity\Booking
         User:
             class: App\Entity\User
         Author:
             class: App\Entity\Author
         BlogPost:
             class: App\Entity\BlogPost